# Generated by Django 2.1.4 on 2018-12-15 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ack_text', models.CharField(max_length=1024)),
                ('action_template', models.CharField(max_length=1024)),
                ('is_leaf', models.BooleanField(default=False)),
                ('priority', models.BigIntegerField()),
                ('prompt_text', models.TextField()),
                ('parent_node', models.BigIntegerField()),
                ('title', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+917760601643'. Up to 13 digits allowed.", regex='^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[6789]\\d{9}$')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('permanent_addr', models.TextField(null=True)),
                ('current_addr', models.TextField(null=True)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('dl_number', models.CharField(max_length=15)),
                ('birth_certificate_serial', models.CharField(max_length=1024)),
                ('date_of_birth', models.DateTimeField()),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='chatline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User'),
        ),
    ]
