# Generated by Django 2.1.4 on 2018-12-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20181215_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatline',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.User'),
            preserve_default=False,
        ),
    ]
