# Generated by Django 2.1.4 on 2018-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_chatline_is_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='treenode',
            name='ack_text',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='action_template',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='parent_node',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='priority',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='prompt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
