# Generated by Django 2.1.4 on 2018-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20181215_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
