# Generated by Django 2.1.4 on 2018-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_treenode_is_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
